const lines = [
  "Are you a magician, Mrinali? Because whenever I look at you, everyone else disappears.",
  "Is your name Mrinali or is it just 'Mine'?",
  "If perfection had a name, it would definitely be Mrinali.",
  "Are you a dictionary, Mrinali? Because you add meaning to my life.",
  "Are you the sun, Mrinali? Because my world revolves around you.",
  "Are you a camera, Mrinali? Because every time I look at you, I smile.",
  "Are you Wi-Fi, Mrinali? Because I’m feeling a very strong connection.",
  "Is there an airport nearby, Mrinali, or is that just my heart taking off?",
  "Are you a star, Mrinali? Because you’re the brightest thing in my sky.",
  "Are you a puzzle, Mrinali? Because you’re my missing piece.",
  "Are you a song, Mrinali? Because you’ve been stuck in my head all day.",
  "Is your middle name 'Grace', Mrinali? Because you move through my heart so elegantly.",
  "Are you a bank loan, Mrinali? Because you have my interest.",
  "Are you a keyboard, Mrinali? Because you’re just my type.",
  "Are you a map, Mrinali? Because I just got lost in your eyes.",
  "Are you a garden, Mrinali? Because I’m digging you.",
  "Are you a lightbulb, Mrinali? Because you brighten up my darkest days.",
  "Are you a passport, Mrinali? Because you’re taking me to a whole new world.",
  "Are you a bookmark, Mrinali? Because I never want to finish this chapter with you.",
  "Are you a snowflake, Mrinali? Because you’re one of a kind.",
  "Are you a telescope, Mrinali? Because you’ve brought my dreams closer.",
  "Are you a masterpiece, Mrinali? Because I could admire you for a lifetime.",
  "Are you a compass, Mrinali? Because you always lead me home.",
  "Are you a sunrise, Mrinali? Because you make my mornings worth waking up for.",
  "Are you a campfire, Mrinali? Because you’re warm and I want s'more of you.",
  "Are you a rainbow, Mrinali? Because you’ve brought color into my life.",
  "Are you a ticket, Mrinali? Because you’ve got 'fine' written all over you.",
  "Are you a spark, Mrinali? Because you’ve started a fire in my soul.",
  "Are you a melody, Mrinali? Because your voice is my favorite sound.",
  "Are you a moon, Mrinali? Because even in my darkest nights, you shine.",
  "Are you a anchor, Mrinali? Because you keep me grounded.",
  "Are you a secret, Mrinali? Because I want to keep you forever.",
  "Are you a diamond, Mrinali? Because you’re rare and precious.",
  "Are you a butterfly, Mrinali? Because you give me butterflies every time.",
  "Are you a poem, Mrinali? Because you’re the most beautiful thing I’ve ever read.",
  "Are you a heartbeat, Mrinali? Because I can’t live without you.",
  "Are you a cloud, Mrinali? Because you’re a dream I never want to wake up from.",
  "Are you a pillow, Mrinali? Because I feel so safe when I’m with you.",
  "Are you a lighthouse, Mrinali? Because you guide me through the storm.",
  "Are you a magnet, Mrinali? Because I’m irresistibly drawn to you.",
  "Are you a wish, Mrinali? Because you’re everything I’ve ever wanted.",
  "Are you a thief, Mrinali? Because you just stole my heart.",
  "Are you a mirror, Mrinali? Because I see my better half in you.",
  "Are you a trophy, Mrinali? Because you’re the best prize I’ve ever won.",
  "Are you a pilot, Mrinali? Because you’ve taken my heart to the clouds.",
  "Are you a scientist, Mrinali? Because our chemistry is undeniable.",
  "Are you a sailor, Mrinali? Because you’ve anchored my soul.",
  "Are you a runner, Mrinali? Because you’ve been running through my mind all day.",
  "Are you a baker, Mrinali? Because you’re such a cutie pie.",
  "Are you a writer, Mrinali? Because you’re my favorite story.",
  "Are you a doctor, Mrinali? Because you just cured my bad mood.",
  "Are you a teacher, Mrinali? Because you’ve taught me how to truly love.",
  "Are you a traveler, Mrinali? Because I want to go anywhere with you.",
  "Are you a movie, Mrinali? Because I want to watch you on repeat.",
  "Are you a galaxy, Mrinali? Because you’re vast and beautiful.",
  "Are you a planet, Mrinali? Because I want to orbit around you forever.",
  "Are you a universe, Mrinali? Because you’re my everything.",
  "Are you a smile, Mrinali? Because you’re the reason for mine.",
  "Are you a laugh, Mrinali? Because you’re my favorite music.",
  "Are you a kiss, Mrinali? Because you’re the sweetest thing I know.",
  "Are you mine, Mrinali? Because I’m definitely yours.",
  "Are you a pearl, Mrinali? Because you’re a treasure I found in the deep.",
  "Are you a firework, Mrinali? Because you make my heart explode with joy.",
  "Are you a lighthouse, Mrinali? Because you’re the only light I see.",
  "Are you a dream, Mrinali? Because I’m afraid to wake up without you.",
  "Are you a treasure map, Mrinali? Because I’ve finally found my gold.",
  "Are you a lucky charm, Mrinali? Because I feel so blessed to know you.",
  "Are you a miracle, Mrinali? Because you’re too good to be true.",
  "Are you a gravity, Mrinali? Because I’m falling for you harder every day.",
  "Are you a horizon, Mrinali? Because you’re where my heaven meets the earth.",
  "Are you a melody, Mrinali? Because I want to sing your name forever.",
  "Are you a masterpiece, Mrinali? Because God was showing off when He made you.",
  "Are you a candle, Mrinali? Because you light up my world.",
  "Are you a blanket, Mrinali? Because you make me feel warm and fuzzy.",
  "Are you a sunrise, Mrinali? Because you’re the start of something beautiful.",
  "Are you a key, Mrinali? Because you’ve unlocked a side of me I never knew.",
  "Are you a melody, Mrinali? Because you make my soul dance.",
  "Are you a star chart, Mrinali? Because you show me the way.",
  "Are you a glass of water, Mrinali? Because you’re exactly what I need.",
  "Are you a sunset, Mrinali? Because you’re the perfect end to any day.",
  "Are you a constellation, Mrinali? Because you’re written in my stars.",
  "Are you a heartbeat, Mrinali? Because you’re the rhythm of my life.",
  "Are you a poet, Mrinali? Because you make my life rhyme.",
  "Are you a bridge, Mrinali? Because you’ve connected my heart to happiness.",
  "Are you a diary, Mrinali? Because I want to share every secret with you.",
  "Are you a firefly, Mrinali? Because you light up my darkest nights.",
  "Are you a slow dance, Mrinali? Because I want to stay in your arms forever.",
  "Are you a fountain, Mrinali? Because your love keeps overflowing in me.",
  "Are you a snowflake, Mrinali? Because you’ve melted my heart.",
  "Are you a bookmark, Mrinali? Because I’ll always save your place.",
  "Are you a vintage record, Mrinali? Because you have so much soul.",
  "Are you a sunrise, Mrinali? Because you bring light to my life.",
  "Are you a secret garden, Mrinali? Because I’m lost in your beauty.",
  "Are you a deep breath, Mrinali? Because you’re the air I need.",
  "Are you a lucky star, Mrinali? Because you’ve made all my wishes come true.",
  "Are you a guardian angel, Mrinali? Because you’re always looking out for my heart.",
  "Are you a compass, Mrinali? Because no matter where I go, I end up with you.",
  "Are you a diamond, Mrinali? Because you’re brilliant in every way.",
  "Are you a masterpiece, Mrinali? Because you’re the only one of your kind.",
  "Are you Mrinali? Because you’re the only one for me.",
  "4+4=8 but you+me=fate",
  "Are you tired? You've been running through my mind all day.",
  "What's your favorite drink? I'm asking so I know what to buy you when we go on our first date.",
  "I should complain to Spotify for not making you this week's hottest single.",
  "Do you play soccer? Because you're a keeper.",
  "You look so familiar…did we have class together? I could've sworn we had chemistry.",
  "I'm learning about important dates in history, wanna be one of them?",
  "Can I show your profile to my friends to prove that angels really do exist?",
  "Are you Gravity? Because I’m falling for you",
  "Are you the horizon? Because I’d travel to the ends of the earth just to reach you.",
  "Are you a solar eclipse? Because I can't look away, even if I should.",
  "Are you an inkwell? Because you’ve written yourself into every chapter of my life.",
  "Are you the tide? Because no matter how far I go, you always pull me back.",
  "Are you a midnight conversation? Because you’re the only thing I want to hear when the world is quiet.",
  "Are you a paper plane? Because you’ve carried my heart further than I ever thought possible.",
  "Are you a locket? Because I want to keep you close to my chest forever.",
  "Are you the first frost? Because you’ve made everything beautiful and still.",
  "Are you a constellation? Because I’ve spent my whole life trying to find a pattern as beautiful as you.",
  "Are you a handwritten letter? Because you’re a rare kind of beautiful in a digital world.",
  "Are you the golden hour? Because you make everything look like a dream.",
  "Are you a lighthouse? Because you’re the only light I look for when I’m lost at sea.",
  "Are you a compass rose? Because no matter which way I turn, I’m headed toward you.",
  "Are you a vintage record? Because I want to listen to your soul on repeat.",
  "Are you the silence between the notes? Because you’re the part of the song that moves me most.",
  "Are you a sanctuary? Because I feel at peace the moment I step into your presence.",
  "Are you a masterpiece in an empty gallery? Because I could stand and admire you for a lifetime.",
  "Are you the gravity of a star? Because my whole world revolves around your light.",
  "Are you a secret garden? Because I want to spend forever getting lost in you.",
  "Are you a telescope? Because you’ve brought the most distant dreams within my reach.",
  "Are you the North Star? Because when everything else changes, you’re the only thing that stays true.",
  "Are you a deep-sea pearl? Because I’d dive into the unknown just to find you.",
  "Are you the smell of rain on dry earth? Because you’re the relief I’ve been waiting for.",
  "Are you a bookmark? Because I never want to finish the story we’re writing.",
  "Are you the morning mist? Because you’ve softened every edge of my world.",
  "Are you a slow dance? Because I want this moment to last forever.",
  "Are you an heirloom? Because you’re the most precious thing I’ll ever hold.",
  "Are you the warmth of a fireplace? Because you’re the only place I want to be when it’s cold outside.",
  "Are you a prism? Because you take the simplest light and turn it into a rainbow.",
  "Are you a velvet night? Because I want to wrap myself in the thought of you.",
  "Are you the ink in my pen? Because I can't express myself without you.",
  "Are you a bridge? Because you’ve connected my past to a future I actually want to see.",
  "Are you the moon’s reflection? Because even in the dark, you show me there is beauty.",
  "Are you a mountain peak? Because you’re the highest point of my life.",
  "Are you a candle in the window? Because you always lead me back home.",
  "Are you a deep breath? Because you’re the first thing I need to feel alive.",
  "Are you a telescope? Because you’ve shown me galaxies I didn't know existed.",
  "Are you a quiet forest? Because I find my truest self when I’m with you.",
  "Are you the echo in a canyon? Because my heart keeps calling your name.",
  "Are you a sundial? Because my time only moves when you’re shining.",
  "Are you a glass of wine? Because you get better and more intoxicating with every moment.",
  "Are you a handwritten note? Because you’re the only thing I want to keep under my pillow.",
  "Are you a soft breeze? Because you’ve carried away all my worries.",
  "Are you a symphony? Because every part of you works in perfect harmony.",
  "Are you a desert bloom? Because you’re a miracle in the middle of nowhere.",
  "Are you the wood fire? Because I can feel your warmth even when I’m not touching you.",
  "Are you an old soul? Because it feels like I’ve loved you for a hundred lifetimes.",
  "Are you a sketch? Because I can see our future taking shape every time we talk.",
  "Are you the sea? Because I’m drowning in the depth of who you are.",
  "Are you a sanctuary? Because the world can’t hurt me when I’m with you.",
  "Are you the rhythm of the rain? Because you’re the soundtrack to my peace.",
  "Are you a shooting star? Because I’ve spent my life waiting for a moment like this.",
  "Are you the poetry of the earth? Because you’re the reason I believe in beauty.",
  "Are you a map to a hidden treasure? Because I’ve finally found what I was looking for.",
  "Are you a silk thread? Because you’ve woven yourself into the fabric of my heart.",
  "Are you the first light of dawn? Because you’ve ended my longest night.",
  "Are you a quiet prayer? Because you’re the answer I didn't know I needed.",
  "Are you a masterpiece? Because I could study you forever and still find something new to love.",
  "Are you the roots of a tree? Because you’re the reason I stand so tall.",
  "Are you a gentle wave? Because you’ve smoothed out all my rough edges.",
  "Are you a time capsule? Because you hold all the things I want to keep forever.",
  "Are you the key to a music box? Because you make my heart dance to your tune.",
  "Are you a sunset over the ocean? Because you’re a beauty that takes my breath away every single time.",
  "Are you a compass? Because without you, I’m just wandering.",
  "Are you the air in a balloon? Because you’ve lifted me off the ground.",
  "Are you a silver lining? Because you’re the best part of every cloudy day.",
  "Are you the spark in the flint? Because you’ve started a fire that will never go out.",
  "Are you a fountain? Because your love is a constant overflow in my life.",
  "Are you the North Wind? Because you’ve blown me in a direction I never expected to go.",
  "Are you a diary? Because you’re the only one I want to tell my secrets to.",
  "Are you the anchor? Because you’re the only thing that keeps me from drifting away.",
  "Are you a harvest moon? Because you’re full of a light that feels like home.",
  "Are you a melody in a minor key? Because you’re hauntingly beautiful and I can’t forget you.",
  "Are you the scent of lavender? Because you’re the only thing that calms my restless heart.",
  "Are you a glass of water in a desert? Because you’re the only thing I truly crave.",
  "Are you a telescope? Because you’ve made my dreams look like reality.",
  "Are you a bridge over a river? Because you’ve helped me cross into a better life.",
  "Are you the heartbeat of the world? Because everything feels alive when you’re near.",
  "Are you a soft sweater? Because I just want to be wrapped up in you all day.",
  "Are you a firefly? Because even in the darkest woods, you show me the way.",
  "Are you a piece of driftwood? Because you’ve finally landed on the shore of my heart.",
  "Are you the snow? Because you’ve turned my world into a quiet, white wonderland.",
  "Are you a constellation? Because I’ve memorized every part of you.",
  "Are you the pages of my favorite book? Because I want to read you until I know you by heart.",
  "Are you a slow-burning candle? Because your light is steady and warm.",
  "Are you the ocean’s song? Because I could listen to you for an eternity.",
  "Are you a mountain path? Because you’re a journey I’d take every single day.",
  "Are you the sun through the leaves? Because you’re the most beautiful light I’ve ever seen.",
  "Are you a hidden cove? Because you’re my secret place to escape.",
  "Are you a wildflower? Because you’re untamed and breathtakingly beautiful.",
  "Are you the ink on a love letter? Because you’re the most important thing ever written.",
  "Are you a star chart? Because you show me where I am and where I’m going.",
  "Are you the first sip of coffee? Because you’re the only way I want to start my day.",
  "Are you a velvet ribbon? Because you’ve tied my heart in knots.",
  "Are you the warmth of the sun on my back? Because you’re the comfort I always seek.",
  "Are you a deep valley? Because your love is deep and sheltering.",
  "Are you a bridge between worlds? Because you’ve shown me a life I never dreamed of.",
  "Are you a lighthouse lens? Because you focus all my love into one point.",
  "Are you a vintage photograph? Because you’re a memory I want to keep forever.",
  "Are you the soul of the world? Because without you, nothing would make sense.",
  "Are you a high-definition screen, Mrinali? Because my life looks so much clearer with you. ✨",
  "If my heart were a program, Mrinali, you’d be the main function. 💻",
  "Are you an oasis, Mrinali? Because you’re the only thing I see in this desert. 🏝️",
  "Is your name Mrinali? Because you’ve got 'forever' written all over you. ♾️",
  "Are you a lightning bolt, Mrinali? Because you just sent a shock through my system. ⚡",
  "Are you a midnight snack, Mrinali? Because you’re all I can think about when the world is quiet. 🍕",
  "Are you a coffee bean, Mrinali? Because you ground me and give me energy. ☕",
  "Are you the North Star, Mrinali? Because you’re the only constant in my sky. 🌌",
  "Are you an eclipse, Mrinali? Because you’re a rare and beautiful sight I can’t stop watching. 🌑",
  "Is your smile patented, Mrinali? Because it’s one of a kind. 😊",
  "Are you a velvet ribbon, Mrinali? Because you’ve tied my heart in the sweetest knots. 🎀",
  "Are you a software license, Mrinali? Because I want to be yours for a lifetime. 📜",
  "Are you a deep-sea pearl, Mrinali? Because you’re worth every risk to find. 🐚",
  "Are you a firefly, Mrinali? Because you bring a little bit of magic to my darkest nights. ✨",
  "Are you a telescope, Mrinali? Because you make all my distant dreams feel reachable. 🔭",
  "Are you a symphony, Mrinali? Because every little thing you do is in perfect harmony. 🎶",
  "Are you an old soul, Mrinali? Because it feels like I’ve loved you since time began. ⏳",
  "Are you a silver lining, Mrinali? Because you’re the best part of every storm. 🌤️",
  "Are you a prism, Mrinali? Because you take my simple life and make it colorful. 🌈",
  "Are you a masterpiece, Mrinali? Because I could spend a thousand years just studying you. 🖼️",
  "Are you a sanctuary, Mrinali? Because I feel totally safe when I'm near you. 🏰",
  "Are you a shooting star, Mrinali? Because I’ve been waiting a lifetime for a chance like this. 🌠",
  "Are you a quiet forest, Mrinali? Because you’re where I find my peace. 🌲",
  "Are you a handwritten note, Mrinali? Because you’re more special than anything digital. ✉️",
  "Are you the morning dew, Mrinali? Because you make everything feel fresh and new. 🍃",
  "Are you a time machine, Mrinali? Because every moment with you feels like forever. 🕰️",
  "Are you a lighthouse, Mrinali? Because you’re the only light I look for when I’m lost. 🚨",
  "Are you an anchor, Mrinali? Because you keep my heart from drifting away. ⚓",
  "Are you a secret garden, Mrinali? Because you’re a beauty the world doesn’t deserve to see. 🌹",
  "Are you a melody, Mrinali? Because you’re the song my heart has been humming forever. 🎵",
  "Are you a gold medal, Mrinali? Because you’re the only prize I’m racing for. 🥇",
  "Are you a compass, Mrinali? Because no matter where I turn, I’m headed toward you. 🧭",
  "Are you a bookmark, Mrinali? Because I never want to lose my place in your life. 🔖",
  "Are you a velvet night, Mrinali? Because I want to get lost in the thought of you. 🌙",
  "Are you a sunrise, Mrinali? Because you’re the only reason I want to wake up early. 🌅",
  "Are you a warm sweater, Mrinali? Because you’re the only comfort I need. 🧶",
  "Are you a harvest moon, Mrinali? Because you light up my world like nothing else. 🌕",
  "Are you a map, Mrinali? Because you’ve led me straight to where I belong. 🗺️",
  "Are you a heartbeat, Mrinali? Because you’re the only thing keeping me going. 💓",
  "Are you a treasure, Mrinali? Because I feel like the luckiest person just knowing you. 💰",
  "Are you an arrow, Mrinali? Because you’ve pierced right through my heart. 💘",
  "Are you a candle, Mrinali? Because you melt me with just a look. 🕯️",
  "Are you a soft breeze, Mrinali? Because you just swept me off my feet. 🌬️",
  "Are you a galaxy, Mrinali? Because there’s so much to discover in your eyes. 🌌",
  "Are you a diamond, Mrinali? Because you’re tough, rare, and absolutely brilliant. 💎",
  "Are you a fountain, Mrinali? Because your kindness never runs dry. ⛲",
  "Are you a poet, Mrinali? Because you make even the simplest days feel like art. 🖋️",
  "Are you a bridge, Mrinali? Because you’ve brought me to the better side of life. 🌉",
  "Are you a diary, Mrinali? Because I want to share every single day with you. 📔",
  "Are you a horizon, Mrinali? Because you’re the perfect meeting of heaven and earth. 🌅",
  "Are you a sparkler, Mrinali? Because you make my heart pop with joy. 🎆",
  "Are you a slow dance, Mrinali? Because I want to stay right here in your rhythm. 💃",
  "Are you a secret, Mrinali? Because you’re the one thing I want to keep forever. 🤫",
  "Are you a raindrop, Mrinali? Because you’ve fallen right into my soul. 💧",
  "Are you a key, Mrinali? Because you’ve unlocked a happiness I never knew. 🔑",
  "Are you a telescope, Mrinali? Because you’ve shown me a whole new universe. 🪐",
  "Are you a sketch, Mrinali? Because I see my future taking shape in your smile. 🎨",
  "Are you a melody in a minor key, Mrinali? Because you’re hauntingly beautiful. 🎻",
  "Are you a silk thread, Mrinali? Because you’ve woven yourself into my heart. 🧵",
  "Are you a miracle, Mrinali? Because people like you shouldn't exist in the real world. ✨",
  "Are you a star chart, Mrinali? Because you’re the map to my destiny. 🗺️",
  "Are you a cup of tea, Mrinali? Because you’re exactly what I need on a rainy day. 🍵",
  "Are you a velvet pillow, Mrinali? Because resting with you is a dream. ☁️",
  "Are you a lighthouse lens, Mrinali? Because you focus all my attention. 🔦",
  "Are you a vintage photo, Mrinali? Because I want to keep this memory forever. 📸",
  "Are you a constellation, Mrinali? Because you’re written in my destiny. ✨",
  "Are you a heartbeat, Mrinali? Because you’re the only pulse I feel. ❤️",
  "Are you a smile, Mrinali? Because you’re the highlight of my day. 🌟",
  "Are you a laugh, Mrinali? Because you’re the only sound I want to hear. 🎶",
  "Are you a kiss, Mrinali? Because you’re the sweetest thing I’ve ever known. 💋",
  "Are you mine, Mrinali? Because I’m definitely yours already. 🔒",
  "Are you a snowflake, Mrinali? Because you’ve landed on my heart and melted it. ❄️",
  "Are you a summer day, Mrinali? Because you make everything feel bright. ☀️",
  "Are you a secret password, Mrinali? Because only you have access to my heart. 🔓",
  "Are you a power-up, Mrinali? Because you make me feel like I can take on the world. ⚡",
  "Are you a save point, Mrinali? Because I always feel safe coming back to you. 💾",
  "Are you a high score, Mrinali? Because you’re the best I’ve ever seen. 🏆",
  "Are you an artist, Mrinali? Because you’ve colored my world perfectly. 🖌️",
  "Are you a pilot, Mrinali? Because you’ve got my heart flying high. ✈️",
  "Are you a sailor, Mrinali? Because you’ve finally brought my heart to shore. ⛵",
  "Are you a runner, Mrinali? Because you’ve been chasing my thoughts all night. 🏃‍♂️",
  "Are you a baker, Mrinali? Because you’re such a sweet treat. 🧁",
  "Are you a teacher, Mrinali? Because you’ve taught me what real love is. 🍎",
  "Are you a traveler, Mrinali? Because I’d go anywhere as long as you’re there. 🌍",
  "Are you a movie, Mrinali? Because I want to watch your life unfold beside mine. 🎬",
  "Are you a song, Mrinali? Because I’ve got you on repeat in my mind. 🎧",
  "Are you a poem, Mrinali? Because every line about you is beautiful. 📜",
  "Are you a star, Mrinali? Because you’re the only thing that guides me through the dark. ⭐",
  "Are you a moon, Mrinali? Because you’re the light in my night sky. 🌙",
  "Are you a sun, Mrinali? Because you’re the center of my world. ☀️",
  "Are you a planet, Mrinali? Because I just want to orbit around you. 🪐",
  "Are you a comet, Mrinali? Because you’re a once-in-a-lifetime kind of person. ☄️",
  "Are you a heart, Mrinali? Because I can’t beat without you. 💓",
  "Are you a soul, Mrinali? Because you’re the better half of who I am. 👤",
  "Are you a breath, Mrinali? Because you’re the air I need to survive. 🌬️",
  "Are you a lucky charm, Mrinali? Because everything goes right when I'm with you. 🍀",
  "Are you a lighthouse, Mrinali? Because you show me the way when I’m lost. ⚓",
  "Are you a guardian angel, Mrinali? Because you always keep my heart safe. 😇",
  "Are you a diamond, Mrinali? Because you’re rare, brilliant, and forever. 💎",
  "Are you the one, Mrinali? Because my heart says you’re the only one. ❤️",
];

function showLine() {
  const lineElem = document.getElementById("line");
  // Show animated dots using CSS and loading text
  lineElem.innerHTML =
    '<div style="display:flex; flex-direction:column; align-items:center;">' +
    '<span style="font-size:1.1rem; color:#ff3b6f; margin-bottom:8px; letter-spacing:0.5px;">Loading: Mrinali’s Smile</span>' +
    '<span class="dots-loading"><span>.</span><span>.</span><span>.</span></span>' +
    '</div>';
  setTimeout(() => {
    const randomIndex = Math.floor(Math.random() * lines.length);
    lineElem.innerText = lines[randomIndex];
  }, 1000);
}

// Initial load
showLine();

// Button click
document.getElementById("generateBtn").addEventListener("click", showLine);
